import html2pdf from "html2pdf.js";
import dayjs from "dayjs";

const generateProjectPdf = (user, selectedDate, projectName, pdfData) => {
  console.log(pdfData); // Log project data

  const generateTaskList = (tasks) => {
    return tasks
      .map(
        (task, i) => `
          <li style=" padding: 10px; border-radius: 5px; margin: 5px 0;">
            ${++i}. <span  style="text-decoration: ${task.Done ? "line-through" : "none"}">${task.Task}</span>  
            <span class="categoryLevel"> ${task.Priority}</span>
          </li>
        `
      )
      .join("");
  };

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Project Task Report</title>
      <style>
        body {
          font-family: 'Helvetica Neue', Arial, sans-serif;
          color: #333;
        }
        h2, h3, h4 {
          color: #2c3e50;
        }
        .info-section {
          display: flex;
          justify-content: space-between;
          margin-bottom: 30px;
          border-bottom: 2px solid #2c3e50;
          padding-bottom: 10px;
        }
        .projectheading{
            margin-bottom:12px;
        }
        .info-section div {
          width: 45%;
        }
        .task-section {
          margin-bottom: 20px;
          }
        .task-section .categoryLevel{
          background-color: #ff7676 ;
          color:white;
          padding:2px 10px;
          border-radius:5px;
          position:absolute;
          right:30px;
          font-weight:bold;
        }
        .task-section h3 {
           width:max-width;  
           color: black;
           padding: 10px;
           border-radius: 5px;
           margin-bottom: 10px;
        }
        .task-section ul {
          list-style: none;
          padding: 10px;
          background-color:whitesmoke;
           border-radius: 10px;
        }
        .task-section li {
          padding: 10px;
          border-radius: 5px;
          margin: 5px 0;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          font-size: 12px;
          color: #888;
        }
      </style>
    </head>
    <body>
      <h2 class="projectheading">Project Task Report</h2>
      <div class="info-section">
        <div>
        <h4>Project: ${projectName}</h4>
          <p>Date: ${dayjs(selectedDate).format("DD-MM-YYYY")}</p>
        </div>
      </div>

      ${pdfData.projecttaspdfklist.length > 0
      ? `
          <div class="task-section">
            <h3>Personal Project Tasks:</h3>
            <ul>${generateTaskList(pdfData.projecttaspdfklist)}</ul>
          </div>
        `
      : "<p>No tasks available for this project.</p>"
    }

      <div class="footer">
        <p>Generated by ActoToDo List</p>
      </div>
    </body>
    </html>
  `;

  // PDF generation options
  const opt = {
    margin: 1,
    filename: `Project_Report_${dayjs(selectedDate).format("DD-MM-YYYY")}.pdf`,
    image: { type: "jpeg", quality: 0.9 },
    html2canvas: { scale: 10 },
    jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
  };

  // Create a temporary container for the HTML content
  const tempContainer = document.createElement("div");
  tempContainer.innerHTML = htmlContent;
  document.body.appendChild(tempContainer);

  // Convert the HTML to PDF
  html2pdf()
    .from(tempContainer)
    .set(opt)
    .save()
    .finally(() => {
      document.body.removeChild(tempContainer);
    });

  // const newWindow = window.open("", "_blank");
  // newWindow.document.write(htmlContent);
  // newWindow.document.close();
};

export default generateProjectPdf;
